[package]
name = "bitset"
version = "0.1.0"
edition = "2021"

[lib]
name = "bitset"

[profile.dev]
overflow-checks = false
opt-level = 3

[lints.rust]
overflowing_literals = "allow"
arithmetic_overflow = "allow"
